apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ornob
data:
  ME_CONFIG_MONGODB_SERVER: "mongo"
  ME_CONFIG_MONGODB_URL: "mongodb://ostad:ostad@mongo:27017"
  MONGO_URI: "mongodb://ostad:ostad@mongo:27017/ostad"
  PORT: "5000"
  VITE_API_URL: "http://ostad-server:5000"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ornob
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: ostad
  MONGO_INITDB_ROOT_PASSWORD: ostad
  ME_CONFIG_MONGODB_ADMINUSERNAME: ostad
  ME_CONFIG_MONGODB_ADMINPASSWORD: ostad